# Generated by Django 6.0.2 on 2026-06-08 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_customteam_teamplayer_customteam_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_name', models.CharField(max_length=100)),
                ('win_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations_as_team_a', to='players.customteam')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations_as_team_b', to='players.customteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
