# Generated by Django 6.0.2 on 2026-06-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('games', models.IntegerField()),
                ('minutes_per_game', models.FloatField()),
                ('points_per_game', models.FloatField()),
                ('rebounds_per_game', models.FloatField()),
                ('assists_per_game', models.FloatField()),
                ('steals_per_game', models.FloatField()),
                ('blocks_per_game', models.FloatField()),
                ('turnovers_per_game', models.FloatField()),
                ('fg_pct', models.FloatField()),
                ('three_pct', models.FloatField()),
                ('ft_pct', models.FloatField()),
                ('offensive_rating', models.FloatField()),
                ('defensive_rating', models.FloatField()),
                ('net_rating', models.FloatField()),
                ('true_shooting_pct', models.FloatField()),
                ('usage_rate', models.FloatField()),
                ('plus_minus', models.FloatField()),
                ('finals_appearances', models.IntegerField()),
                ('championships', models.IntegerField()),
                ('era', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.player')),
            ],
        ),
    ]
