def build_matchup_explanation_prompt(analytics_data):
    """
    Builds the prompt explaining the matchup simulation results.
    """
    sim = analytics_data['simulation']
    team_a = analytics_data['team_a_analytics']
    team_b = analytics_data['team_b_analytics']
    awards = analytics_data['player_awards']

    matchups_text = ""
    for item in sim['position_matchups']:
        matchups_text += f"- {item['position']}: {item['player_a']} ({item['score_a']}) vs {item['player_b']} ({item['score_b']}) -> Advantage: {item['winner']} ({item['advantage']})\n"

    prompt = f"""
You are an expert NBA Analyst. Explain the following matchup simulation results generated by our system.
Remember: Do NOT calculate or change any winner, probability, or ratings. Your job is ONLY to explain why these results occurred based on the data.

### MATCHUP OVERVIEW
- Team A: {sim['team_a']['name']} (Rating: {sim['team_a']['rating']}, Win Prob: {sim['team_a']['win_probability'] * 100:.2f}%)
- Team B: {sim['team_b']['name']} (Rating: {sim['team_b']['rating']}, Win Prob: {sim['team_b']['win_probability'] * 100:.2f}%)
- Predicted Winner: {sim['predicted_winner']}
- Offensive Advantage: {sim['offensive_advantage']}
- Defensive Advantage: {sim['defensive_advantage']}

### TEAM A STATISTICS & ANALYTICS
- Average Age: {team_a['overview']['avg_age']}
- Average Height: {team_a['overview']['avg_height_inches']} inches
- Average Weight: {team_a['overview']['avg_weight_lbs']} lbs
- Average Points Per Game: {team_a['offensive_profile']['avg_points_per_game']}
- Average Offensive Rating: {team_a['offensive_profile']['avg_offensive_rating']}
- Average True Shooting %: {team_a['offensive_profile']['avg_true_shooting_pct']}%
- Average Defensive Rating: {team_a['defensive_profile']['avg_defensive_rating']}
- Strengths: {", ".join(team_a['strengths'])}
- Weaknesses: {", ".join(team_a['weaknesses'])}

### TEAM B STATISTICS & ANALYTICS
- Average Age: {team_b['overview']['avg_age']}
- Average Height: {team_b['overview']['avg_height_inches']} inches
- Average Weight: {team_b['overview']['avg_weight_lbs']} lbs
- Average Points Per Game: {team_b['offensive_profile']['avg_points_per_game']}
- Average Offensive Rating: {team_b['offensive_profile']['avg_offensive_rating']}
- Average True Shooting %: {team_b['offensive_profile']['avg_true_shooting_pct']}%
- Average Defensive Rating: {team_b['defensive_profile']['avg_defensive_rating']}
- Strengths: {", ".join(team_b['strengths'])}
- Weaknesses: {", ".join(team_b['weaknesses'])}

### MATCHUP AWARDS
- MVP: {awards['best_player']}
- Best Shooter: {awards['best_shooter']}
- Best Playmaker: {awards['best_playmaker']}
- Best Defender: {awards['best_defender']}

### POSITION MATCHUPS
{matchups_text}

Provide a detailed, professional, and analytical explanation summarizing:
1. Why the predicted winner won.
2. The core tactical advantages (Offensive vs Defensive) that decided the matchup.
3. How individual position battles (e.g. PG vs PG, C vs C) influenced the result.
Write it in a clean, professional, markdown format.
"""
    return prompt

def build_team_improvement_prompt(team_analytics, player_pool):
    """
    Builds the prompt suggesting roster changes based on team weaknesses.
    """
    overview = team_analytics['overview']
    off = team_analytics['offensive_profile']
    df = team_analytics['defensive_profile']
    strengths = team_analytics['strengths']
    weaknesses = team_analytics['weaknesses']

    pool_text = ""
    for p in player_pool:
        pool_text += f"- ID: {p['id']}, Name: {p['player_name']}, Position: {p['position']}, PPG: {p['ppg']}, RPG: {p['rpg']}, APG: {p['apg']}, SPG: {p['spg']}, BPG: {p['bpg']}, TS%: {p['ts_pct'] * 100:.1f}%\n"

    prompt = f"""
You are an NBA General Manager. Suggest roster upgrades to improve this team.
Analyze the team's profiles and recommend specific players from the available pool below to replace current players in order to cover the weaknesses.

### CURRENT TEAM STATS
- Strengths: {", ".join(strengths)}
- Weaknesses: {", ".join(weaknesses)}
- Team Average PPG: {off['avg_points_per_game']}
- Team Average TS%: {off['avg_true_shooting_pct']}%
- Team Average Defensive Rating: {df['avg_defensive_rating']}

### AVAILABLE PLAYER POOL
{pool_text}

Recommend exactly 2 or 3 player replacements. Explain which player to replace, why the new player fits better, and how it directly addresses the team's weaknesses (e.g., boosting shooting, defense, or rebounding).
Write in clean, professional markdown.
"""
    return prompt
